# Generated by Django 5.1.2 on 2025-06-09 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_add_favorite_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
