# Generated by Django 5.1.2 on 2025-06-16 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_payment_stripe_payment_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='stripe_payment_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='stripe_payment_intent_id',
        ),
    ]
